version: '3'

services:
  api:
    container_name: 'api'
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    tty: true
    ports:
      - '8080:8080'
    volumes:
      - ./app:/usr/src/app
    environment:
      TZ: Asia/Tokyo
      LOCAL: 1