FROM python:3.8

WORKDIR /usr/src
COPY . .
# requirements install
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# listen 8000 port...
CMD ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]
